### ISSUE TITLE
UI cleanup and flavor

### ISSUE THREAD

**Issue by p5150j** [AmplicaLabs/social-app-template#73]
As a Product Owner, I want to refresh the UI of our social-app-template to align more with current trends, specifically taking inspiration from modern social networks layout, to leverage the momentum from our "current ecosystem" and make our template more appealing and relevant.

Background:
Currently, our social-app-template has a layout similar to X (Twitter). While this layout is functional, there is an opportunity to capitalize on the current buzz surrounding new social networks and its their growth. We can make our template more engaging and relatable to the social networks of 2024.

Objectives:

- Redesign the social-app-template UI to resemble the moden social network web layout while keeping it generic enough to serve as a versatile example for users to interact with the Gateway.
- Ensure the new design aligns with the v1 functionality of Gateway and the social-app-template, maintaining clarity and ease of use.
- Leverage the momentum from our acquisition bid to make the template more appealing and relevant.

Key Considerations:

- Avoid a direct clone of any specific social network layout layout to maintain originality and relevance to our specific use cases.
- Focus on creating a modern and exciting user experience that resonates with users familiar with contemporary social networks.

Action Items:

- Schedule a meeting on Friday or Monday to scope out the redesign. @p5150j @claireolmstead (@wilwade optional)
- Define the elements of a modern social network layout that are most appealing and suitable for our template.
- Develop a plan to integrate these elements in a way that enhances the user experience without compromising the template's primary function as an example for Gateway users while keeping the template generic enough wherein users don't think this is a production application.

**Comment by claireolmstead** [comment]
As discussed with @wilwade and @p5150j , time box to ~5 hours.
