### ISSUE TITLE
BUG: Always display full handle

### ISSUE THREAD

**Issue by claireolmstead** [AmplicaLabs/social-app-template#78]
**Current Behavior:**
- We are displaying a mix of the full handle with the suffix and only the base handle.

**Expected Behavior:**
- We want to always display the full handle.

**Trickle Down Bug:**
Ex: If you're logged in as `user.12` and you click on the avatar of your own post that displays the handle `user` (with no suffix), it navigates you to what seems like a new profile that you're able to follow/unfollow, when in reality it's the same user just with and without the suffix.

**Acceptance Criteria:**
- [ ] Always display the handle with the suffix
- [ ] When navigating from the current user's post to the current user's profile, the Profile section should display the data as the current user and should not have a follow/unfollow button, like when you're viewing a different user's profile.
- [ ] Idea: Can style the suffix to be less bold or slightly transparent so the emphasis is on the base handle.

BLOCKS #80

**Comment by mattheworris** [comment]
Suggestion: this is an account-service bug.
