### ISSUE TITLE
BUG: Avatar Icon

### ISSUE THREAD

**Issue by claireolmstead** [AmplicaLabs/social-app-template#80]
BLOCKED by #78 

As a user, I wish to see an avatar icon, not just a black circle.

**Current Behavior:**
- Avatar is unable to read the numerical suffix, defaulting to a black background. 
- The same avatar should be displayed in following places:
  - Header
  - Profile
  - New Post
  - Post
  - Reply (currently not working)

**Expected Behavior:**
- A colorful avatar is always displayed.

Notes:
- Need to alter the string or use the base handle when rendering the avatar. It doesn't like the `.`.

**Comment by mattheworris** [comment]
Suggestion: this should be coordinated with account-service, it should always return the same version of the handle, probably handle plus suffix.

**Comment by claireolmstead** [comment]
resolved in #78
