### ISSUE TITLE
Post loading indicator

### ISSUE THREAD

**Issue by claireolmstead** [AmplicaLabs/social-app-template#85]
**Current Behavior:**
- There is no indication of the status of a post between when you click "Post" and when it randomly appears a minute or so later in `My Posts`.

**Expected Behavior:**
- If a post is in the queue, display a skeleton post with an aside that it takes the chain ~1 min to process the post.
- Check out loading card: https://ant.design/components/card
- NOT INCLUDED: Need to poll for when the post is received then trigger refresh.

**Dev Notes:**
- Check out what https://ant.design/ offers to achieve this.
- BLOCKS #90

**Comment by mattheworris** [comment]
Backend Context:
- The `content-watcher` runs on a 1 minute interval. The backend does not find out that the post has been successfully announced on the blockchain until the next interval. The content is then cached and is available to the api.
- It may be possible to decrease this polling interval.
